[[headers]]
  for = "/*"
  [headers.values]
    X-Flag-Launch = "3/3 - 'NUZW45C7K4YW4435'"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Set-Cookie = "CyberSAC={G1MM3_C00K13S_N0W}; Path=/; Secure; HttpOnly; SameSite=Strict"
    Pragma = "no-cache"
    Expires = "0"